#!/bin/bash
# Create this fork's own release signing key, once.
#
# Without it `scripts/build_apk.sh` falls back to Android's generic debug key
# (android/app/build.gradle.kts says so explicitly). That key lives in
# ~/.android/debug.keystore, belongs to this Mac rather than to the app, and
# can be regenerated by any tool that feels like it. When it changes, Android
# refuses to update an installed Plebz — the signature no longer matches — and
# the only way forward is uninstall and reinstall.
#
# The keystore goes in the home directory, NOT in the project: the project
# lives under /Users/Shared, which every account on this Mac can read.
#
# Losing this file (or its password) has the same consequence as changing the
# key: no more in-place updates, ever. Back both up somewhere you trust.

set -euo pipefail

KEYSTORE="$HOME/.plebz/plebz-release.jks"
ALIAS="plebz"
PROPERTIES="$(cd "$(dirname "$0")/.." && pwd)/android/key.properties"

JAVA_HOME="${JAVA_HOME:-/Applications/Android Studio.app/Contents/jbr/Contents/Home}"
KEYTOOL="$JAVA_HOME/bin/keytool"

if [ ! -x "$KEYTOOL" ]; then
    echo "Error: keytool not found at $KEYTOOL" >&2
    echo "Set JAVA_HOME to a JDK (Android Studio ships one) and try again." >&2
    exit 1
fi

if [ -e "$KEYSTORE" ]; then
    echo "Error: $KEYSTORE already exists." >&2
    echo "Delete it only if you are certain nothing is signed with it — every" >&2
    echo "install signed by it becomes un-updatable." >&2
    exit 1
fi

# Read twice, never echoed, never passed on a command line: an argument is
# visible to `ps` for as long as the process runs. keytool's `:env` form reads
# it out of the environment instead.
printf 'Passwort für den Schlüssel (wird nicht angezeigt): '
read -rs PLEBZ_KEY_PASSWORD
printf '\nNoch einmal zur Kontrolle: '
read -rs CONFIRM
printf '\n'

if [ "$PLEBZ_KEY_PASSWORD" != "$CONFIRM" ]; then
    echo "Error: die beiden Eingaben stimmen nicht überein." >&2
    exit 1
fi
if [ ${#PLEBZ_KEY_PASSWORD} -lt 8 ]; then
    echo "Error: keytool verlangt mindestens 8 Zeichen." >&2
    exit 1
fi
unset CONFIRM
export PLEBZ_KEY_PASSWORD

mkdir -p "$(dirname "$KEYSTORE")"
chmod 700 "$(dirname "$KEYSTORE")"

# The name carries nothing personal on purpose. Nobody checks it for an app
# that is installed by hand, and it is readable by anyone holding the APK.
#
# PKCS12 (keytool's default) keeps one password for the store and the key, so
# both read the same variable. 10000 days is the span Google recommends for an
# app expected to keep updating.
"$KEYTOOL" -genkeypair \
    -keystore "$KEYSTORE" \
    -storetype PKCS12 \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10000 \
    -dname "CN=Plebz, O=Plebz" \
    -storepass:env PLEBZ_KEY_PASSWORD \
    -keypass:env PLEBZ_KEY_PASSWORD

chmod 600 "$KEYSTORE"

# Gradle reads this file if it exists and signs with the debug key if it does
# not. It holds the password in plain text — that is how Android signing works
# — so it stays out of git (android/.gitignore) and off other accounts' reach.
umask 077
cat > "$PROPERTIES" <<EOF
storeFile=$KEYSTORE
storePassword=$PLEBZ_KEY_PASSWORD
keyAlias=$ALIAS
keyPassword=$PLEBZ_KEY_PASSWORD
EOF
chmod 600 "$PROPERTIES"

unset PLEBZ_KEY_PASSWORD

echo
echo "Keystore:        $KEYSTORE"
echo "Gradle liest:    $PROPERTIES"
echo
echo "Beides sichern. Ohne sie ist kein Update einer installierten Plebz mehr"
echo "möglich — nur noch deinstallieren und neu installieren."
